### ISSUE TITLE
应用go泛型

### ISSUE THREAD

**Issue by thecodeworks** [jefferyjob/go-easy-utils#12]
go.mod中go的版本是1.18，已经支持泛型，为何没有应用泛型，存在大量的重复代码和interface{}。
```go
// MergeSlices 将多个slice合并成一个slice
func MergeSlices(slices ...[]interface{}) []interface{} {}

// MergeStrSlices 将多个slice合并成一个slice
func MergeStrSlices(slices ...[]string) []string {}

// MergeIntSlices 将多个slice合并成一个slice
func MergeIntSlices(slices ...[]int) []int {}
```

可以参考[lancet](https://github.com/duke-git/lancet)

**Comment by jefferyjob** [comment]
非常感谢您提出的建议  
因为项目的开始是基于公司业务发展封装出来的一个包，考虑到向下兼容一些旧的版本，所以没有用到泛型。  
1.0 的版本其实更多的是考虑解决目前本公司内的业务。

最近的工作分为两部分
1. 完善泛型，减少冗余代码
2. 完善sliceUtils包中的方法和增加mathUtils包的支持

所以您提出的问题会在不久后得到支持，请期待后续版本的发布！
