### ISSUE TITLE
`Chunk(slice []interface{}, size int) [][]interface{}`换成any是否会更好?

### ISSUE THREAD

**Issue by XiaoK29** [jefferyjob/go-easy-utils#13]
func Chunk[T any](slice []T, size int) [][]T {
	var chunks [][]T
	for i := 0; i < len(slice); i += size {
		end := i + size
		if end > len(slice) {
			end = len(slice)
		}
		chunks = append(chunks, slice[i:end])
	}
	return chunks
}

**Comment by XiaoK29** [comment]
如果要兼容低版本golang当我没说

**Comment by jefferyjob** [comment]
当然会换的。

将会在 2.0 版本（当前开发中）中更新`泛型`和`any` 
低版本的go让使用 1.0 的这个包

**Comment by jefferyjob** [comment]
> func Chunk[T any](slice []T, size int) [][]T { var chunks [][]T for i := 0; i < len(slice); i += size { end := i + size if end > len(slice) { end = len(slice) } chunks = append(chunks, slice[i:end]) } return chunks }

项目已经全面支持泛型和any
新增了mathUtil

望知悉
