### ISSUE TITLE
过多的使用反射

### ISSUE THREAD

**Issue by XiaoK29** [jefferyjob/go-easy-utils#29]
https://github.com/jefferyjob/go-easy-utils/blob/0811e07c56d1c7697e776214002116ebd4651a15/mathUtil/ceil.go#L9

这种方法完全可以不使用反射，可以这样写func Ceil[T float32 | float64](num T) int {
	if num == 0{return 0 }
	return int(math.Ceil(float64(num)))
}

**Comment by jefferyjob** [comment]
这块的确写的冗余了，感谢指出

**Comment by XiaoK29** [comment]
> 这块的确写的冗余了，感谢指出

mathUtil库都大量使用了没必要的反射

**Comment by jefferyjob** [comment]
> > 这块的确写的冗余了，感谢指出
> 
> mathUtil库都大量使用了没必要的反射

下个版本中优化

**Comment by jefferyjob** [comment]
已优化处理
