### ISSUE TITLE
Can all errors be elevated to predefined types

### ISSUE THREAD

**Issue by the-earth-to** [jefferyjob/go-easy-utils#49]
https://github.com/jefferyjob/go-easy-utils/blob/3c0b9747465ed322a78f7864338fb63a1efac312/jsonUtil/parse_map.go#L100

I think errors like this can be improved to json_ to_ struct. go, it is convenient for developers to make incorrect type assertions

**Comment by jefferyjob** [comment]
I don't think this is a good solution. If defined uniformly, developers will not be able to determine the specific error fields, making it difficult for developers to troubleshoot problems.
If you have any better suggestions, you can leave me a message.

**Comment by the-earth-to** [comment]
If the error returned is accurate to the value of a specific field, I don't think this is a good way to solve the problem. I think it is only necessary to return the specific error field to the developer.

**Comment by jefferyjob** [comment]
Thank you for your suggestion. If you have any questions, please continue to leave a message
